//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-I5022NU;Initial Catalog=QL_CHDoAn;User ID=sa;Password=sa2012")]
        public string QL_CHDoAnConnectionString {
            get {
                return ((string)(this["QL_CHDoAnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-I5JOH50\\SQLEXPRESS;Initial Catalog=QL_CHDoAn;User ID=sa;Passw" +
            "ord=sa2012")]
        public string QL_CHDoAnConnectionString1 {
            get {
                return ((string)(this["QL_CHDoAnConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-I5022NU;Initial Catalog=QL_CHDoAn1;User ID=sa;Password=sa2012" +
            "")]
        public string QL_CHDoAn1ConnectionString {
            get {
                return ((string)(this["QL_CHDoAn1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-I5JOH50\\SQLEXPRESS;Initial Catalog=QL_CHDoAn1;User ID=sa;Pass" +
            "word=sa2012")]
        public string QL_CHDoAn1ConnectionString1 {
            get {
                return ((string)(this["QL_CHDoAn1ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-I5022NU;Initial Catalog=QL_CHDoAn;User ID=sa;Password=sa2012")]
        public string dbQLCHDOAN {
            get {
                return ((string)(this["dbQLCHDOAN"]));
            }
            set {
                this["dbQLCHDOAN"] = value;
            }
        }
    }
}
